### ISSUE TITLE
Some feedback/suggestions for V1

### ISSUE THREAD

**Issue by benedict-odonovan** [SamGowland/Gowla-Macro-Boards#2]
Hi Gowla!

I ordered a PCB and top layer from your eBay store and I only got around to putting it together today as my first attempt at a custom keyboard. Admittedly my soldering leaves something to be desired but it was great fun and the board looks and works great.

Some suggestions if you're interested:

- You may want to look at providing/suggesting larger spacers for the bottom of the board. I socketed my pro micro rather than soldering it directly to the board and it stands too proud from the board for the provided (8mm?) standoffs. I ended up combining the 3mm and 8mm standoffs to fit the pro micro underneath.
- Space for a reset button on the board might be handy as an option
- The instructions don't reference the optional top layer at all so I wasn't sure whether it sat above or below the switches
- More pictures to accompany the instructions would be helpful!

**Comment by SamGowland** [comment]
Thanks for your suggestions, it's greatly apperciated and helpful to me for improving the documentation :)

8mm standoffs should give you enough clearance using a socketed pro micro. However I may have given you 6mm standoffs by accident, which I use for cases.  

**Sorry if this the case**, you can measure them and if they are 6mm contact me through ebay and will post you some 8mm's. 

The optional top just gets placed on top the pcb, with 3mm M2 spacers between the top part and the PCB. It's a decorative add on and so can be added after switches are soldered, when no keycaps are attached. 

And yes a dedicated button could be nice!
