### ISSUE TITLE
Compatibility with ESP8266

### ISSUE THREAD

**Issue by fred2u** [SamGowland/Gowla-Macro-Boards#3]
Hi Gowla,

Is your PCB compatible with a ESP8266 ESP-12F like this one ?

![lolinunverlotetmain_500x](https://user-images.githubusercontent.com/20822875/105113290-eb239680-5ac4-11eb-9765-ee30e7029878.jpg)

Thanks,
Fred

**Comment by SamGowland** [comment]
Hi Fred, 

Thanks for your interest, no it does not support this. The pinout supports a sparkfun or sparrkfun sized clone Pro Micro. 

V1 PCB does not use much of the GPIO, pins 2,3,4 and 7,8,9 are used.  And so you could probably hack a ESP8266 module onto it some how. But theres not much space, so might not be the best candidate for this. 

Likewise eRGB, but with that there's even less room. 

Thanks :)
