### ISSUE TITLE
Easy RGB Extension for V1 PCBs

### ISSUE THREAD

**Issue by benjgorman** [SamGowland/Gowla-Macro-Boards#4]
Hey Sam, Great little PCB, super easy to get working. I'm used to working with Arduino, but new to QMK, and your guide was super easy to follow. I'm using this for a little streamdeck for using with OBS when online teaching.

Your PCB footprint/dimensions perfectly allows for a 24 LED Neopixel ring (NeoPixel Ring - 24 x WS2812 5050 RGB LED with Integrated Drivers). Figured I would add the images here in case it was useful for building future versions. I've just wired the 5V pin to VCC, and then GND and Pin 14 for the Data Input.

<img src="https://user-images.githubusercontent.com/622001/105648667-91e0ac00-5ea4-11eb-81e4-c8283c0387d0.jpg" width="400">

<img src="https://user-images.githubusercontent.com/622001/105648672-96a56000-5ea4-11eb-9d6d-0c6f0d2c6df9.jpg" width="400">

<img src="https://user-images.githubusercontent.com/622001/105648675-9907ba00-5ea4-11eb-957b-cd9ec9378c65.jpg" width="400" >

**Comment by SamGowland** [comment]
Thanks Ben :)

Always enjoy seeing builds and any hacking! 

QMK is great, just the intial hurdle of a build enviroment and then it's smooth sailing. If you happen to make any complex firmware builds please do consider sharing them. You can do this here or within the QMK repo itself. 

I will have some SLA printed cases available soon, if they happen to interest you. There's a picture in the repo. Though with your add on they might not fit. The STL for the cases are available, which you could use to make the case a bit taller so your extra would fit and use an on demand print service. 

eRGB adds encoders and RGB lights, just uses the cutable adhesive 2812 strips. Just cut and stick between the markers on the PCB and solder a bridge across. It works really well. 

MEK Light, I have through hole PCBs at the moment and once tested will put some on the ebay page if interested. 
![DSC_0780](https://user-images.githubusercontent.com/10119462/105702904-61c8f580-5f04-11eb-86c1-d290c879c600.JPG)
