### ISSUE TITLE
2D drawings for the top plate

### ISSUE THREAD

**Issue by UweZiegenhagen** [SamGowland/Gowla-Macro-Boards#6]
Hi Sam, I'd like to cut some veneer for the top plate with a laser cutter and need a 2D vector drawing of the top plate. Do you have some drawing?

**Comment by SamGowland** [comment]
Hi 😄  Sorry for my delay, but you can find STL for the top plate part here https://github.com/SamGowland/Gowla-Macro-Boards/blob/master/STL/top_plate.stl

Along with STL for the bottom part. Hope this helps! 

Likewise some gerbers are available in /Gerbers/ these can be opened in most EDA software.

**Comment by UweZiegenhagen** [comment]
Thank you, that helped. Following the instructions on http://rasterweb.net/raster/2020/05/24/stl-to-svg/ I was able to export a SVG from OpenSCAD

[Gowla_Board_TOP_SVG.zip](https://github.com/SamGowland/Gowla-Macro-Boards/files/6445451/Gowla_Board_TOP_SVG.zip)
